export const request = {
  FETCH_BLOGS: "FETCH_BLOGS",
  FETCH_HOME_BLOGS: "FETCH_HOME_BLOGS",
  PUBLISH_BLOG: "PUBLISH_BLOG",
  FETCH_BLOGS_BY_ID:"FETCH_BLOGS_BY_ID",

  
  FETCH_CATEGORY: "FETCH_CATEGORY",
  ADD_CATEGORY: "ADD_CATEGORY",
  EDIT_CATEGORY: "EDIT_CATEGORY",

  ERROR: "ERROR",
  LOADING: "LOADING",
};
